Cbk13 sitzplatzbuchung
wall0404/coba pull request #34
Opened 2020-12-17 19:09 UTC by hannah1666

Farbe in DateTimeSelection wird geregelt - evtl noch Anpassungen, aber an sich funktioniert

2020-12-17 21:15 UTC, wall0404 requested changes

2020-12-17 21:15 UTC, wall0404 commented on resources/js/components/Pages/Book/Page_DateTimeSelection.vue
> +console.log(this.bookings)
Bitte noch raus nehmen. Keine Test-Ausgaben auf dem Server :)

2020-12-17 21:15 UTC, wall0404 commented on resources/js/components/Elements/DayPicker.vue
> +                        console.log(disabled);
Bitte noch raus nehmen. Keine Test-Ausgaben auf dem Server :)

2020-12-17 22:59 UTC, hannah1666 commented on resources/js/components/Pages/Book/Page_DateTimeSelection.vue
> +console.log(this.bookings)
erledigt :)

2021-01-05 08:44 UTC, wall0404 commented
Wird zusammen mit #35 gemerged

2021-01-05 08:44 UTC, closed without merging