automatische Rückführung
wall0404/coba pull request #35
Opened 2020-12-20 13:33 UTC by dani-0101

countDown variable can be ignored

2020-12-21 10:05 UTC, wall0404 requested changes

2020-12-21 10:05 UTC, wall0404 commented on public/css/app.css
> -/* INPUT Styles */
Warum entfernst du das?
Das muss auf jeden Fall drin bleiben. Zum Beispiel für die Sign Up Page

2020-12-21 10:05 UTC, wall0404 commented on public/css/app.css
> -.coba-form {
Das auch

2020-12-21 13:37 UTC, dani-0101 commented on public/css/app.css
> -/* INPUT Styles */
Ich kann mich nicht erinnern irgendwas an der SCSS Datei verändert zu haben. Die Änderungen die hier angezeigt werden sich bei mir auch nicht vorhanden

2021-01-04 09:11 UTC, wall0404 requested changes

2021-01-04 09:11 UTC, wall0404 commented on resources/sass/coba-ci.scss
> +        background-color: #FF6666 !important;
important raus

2021-01-04 09:11 UTC, wall0404 commented on resources/js/components/Pages/Book/Page_BookingCheckout.vue
> +                            <router-link to="/home"><button class="coba-button coba-button-white coba-button-yellow-border">Zur Startseite</button></router-link>
abstand einfügen
 mt-2

2021-01-04 09:35 UTC, thelinking commented on resources/sass/coba-ci.scss
> +        background-color: #FF6666 !important;
entfernt

2021-01-04 09:36 UTC, thelinking commented on resources/js/components/Pages/Book/Page_BookingCheckout.vue
> +                            <router-link to="/home"><button class="coba-button coba-button-white coba-button-yellow-border">Zur Startseite</button></router-link>
Abstand eingefügt

2021-01-05 07:03 UTC, thelinking commented
Ich muss doch noch was am Design verbessern, habs erstmal zu mir assigned

2021-01-05 10:14 UTC, wall0404 approved these changes

2021-01-05 10:15 UTC, merged